"""rename address

Revision ID: 781aea24385e
Revises: dc7ba5db54bd
Create Date: 2024-07-02 12:10:27.123466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '781aea24385e'
down_revision = 'dc7ba5db54bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address',  new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location',  new_column_name='address')
    # ### end Alembic commands ###